### ISSUE TITLE
VMD 1.9.4 "viewsq package could not be loaded"

### ISSUE THREAD

**Issue by chandanchoudhury** [tmackoy/viewSq#11]
Hi!

I am unable to install and run the viewSq in macOS (11.4).
Error:"The viewsq package could not be loaded:"
Please see the attached image.

![image](https://github.com/tmackoy/viewSq/assets/14907876/0842949f-e0c8-43fb-9323-ccb75006555d)

**Comment by tmackoy** [comment]
This is a known issue and has a ticket here: https://github.com/tmackoy/viewSq/issues/7 

The error message can be ignored. If installed correctly viewSq will be available under Extensions->Analysis.
