### ISSUE TITLE
g(r) and S(q) from the elements.ndx

### ISSUE THREAD

**Issue by chandanchoudhury** [tmackoy/viewSq#12]
Hi!

In the tutorial, the elements.ndx contains the indices of H and O, separately. Does the g(r) and S(q) reported are of H-H or O-O or O-H? Please assist.

Thank you!

**Comment by tmackoy** [comment]
Section 7 of the tutorial shows how to calculate the all atom g(r) and S(q). Section 8 shows how to calculate partial S(q), such as H-H or O-H.
